config/routes.rb
MmlCare::Application.routes.draw do
  get 'mmlca/overview' => 'mmlca#overview'
  get 'mmlca/specification' => 'mmlca#specification'
  get 'mmlca/table' => 'mmlca#table'
  get 'mmlvs/compare_vs_lb' => 'mmlvs#compare_vs_lb'
  get 'mmlvs/specification' => 'mmlvs#specification'
  get 'mmlca/sample_instance' => 'mmlca#sample_instance'
  get 'prescriptions/specification' => 'prescriptions#specification'
  get 'injections/specification' => 'injections#specification'

  resources :prescriptions
  resources :mmlca
  resources :mmlvs
  resources :people
  resources :services
  resources :observations
  resources :intakes
  resources :bodily_outputs
  resources :injections
  resources :regimen
  resources :medications
  resources :archetypes
  resources :nodes
  
  root to: 'mmlca#overview'

end

app/models/archetype.rb
class Archetype < ActiveRecord::Base
end

app/models/bodily_output.rb
class BodilyOutput < ActiveRecord::Base
  self.inheritance_column = :ar_type
end

app/models/injection.rb
class Injection < ActiveRecord::Base
  has_many :regimen

  def batch
    self.regimen.inject({}) do |rp, reg|
      if rp[reg.batch_no].nil?
        rp[reg.batch_no] = [reg]
      else
        rp[reg.batch_no] << reg
      end
      rp
    end
  end

end

app/models/intake.rb
class Intake < ActiveRecord::Base
  self.inheritance_column = :ar_type
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :prescription
end

app/models/mmlca.rb
class Mmlca < ActiveRecord::Base
  has_many :mmlvs
end

app/models/mmlvs.rb
class Mmlvs < ActiveRecord::Base
  has_many :vital_signs
  
  def sbp
    find_scoped_type('Systolic blood pressure')
  end

  def dbp
    find_scoped_type('Diastolic blood pressure')
  end

  def pulse
    find_scoped_type('Pulse rate')
  end

  def bt
    find_scoped_type('Body temperature')
  end

  def save
    vital_signs.each do |vs|
      vs.save
    end
    super
  end

  def update(params)
    VitalSign.create(type: 'Systolic plood pressure', val: params[:sbp], unit: 'mmHg', mmlvs_id: self.id)
    VitalSign.create(type: 'Diastolic blood pressure', val: params[:dbp], unit: 'mmHg',mmlvs_id: self.id)
    VitalSign.create(type: 'Pulse rate', val: params[:pulse], unit: '/min',mmlvs_id: :id)
    VitalSign.create(type: 'Body temperature', val: params[:bt], unit: 'centigrade',mmlvs_id: self.id)
    super
  end

  private

  def find_scoped_type(arg)
    vital_signs.select {|vs| vs.type == arg}.first
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
end

app/models/observation.rb
class Observation < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  has_many :medications

  def batch
    self.medications.inject({}) do |rp, med|
      if rp[med.batchNo].nil?
        rp[med.batchNo] = [med]
      else
        rp[med.batchNo] << med
      end
      rp
    end
  end
end

app/models/regimen.rb
class Regimen < ActiveRecord::Base
  belongs_to :injection
end

app/models/service.rb
class Service < ActiveRecord::Base
  self.inheritance_column = :ar_type
end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
  self.inheritance_column = :ar_type
  belongs_to :mmlvs

#  validates :val, numericality: {greater_than_or_equal_to: 0}
  scope :sbp, ->{ where type: 'Systolic blood pressure'}
#  default_scope { where published: true }
end

app/models/vschart.rb
class Vschart
  include ActiveModel::Model
  attr_accessor :sbp, :dbp, :pulse, :bt
  def initialize(args = { })
    self.sbp = args[:sbp]
    self.dbp = args[:dbp]
    self.pulse = args[:pulse]
    self.bt = args[:bt]
  end
end

app/controllers/mmlca_controller.rb
class MmlcaController < ApplicationController
  before_action :set_mmlca, only: [:show, :edit, :update, :destroy]

  def overview
  end

  def specification
  end

  def table
  end
  
  def sample_instance
  end

  def index
    @mmlca = Mmlca.all
  end

  def show
  end

  # GET /mmlca/new
  def new
    @mmlca = Mmlca.new
  end

  # GET /mmlca/1/edit
  def edit
  end

  # POST /mmlca
  # POST /mmlca.json
  def create
    @mmlca = Mmlca.new(mmlca_params)

    respond_to do |format|
      if @mmlca.save
        format.html { redirect_to @mmlca, notice: 'Mmlca was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mmlca }
      else
        format.html { render action: 'new' }
        format.json { render json: @mmlca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mmlca/1
  # PATCH/PUT /mmlca/1.json
  def update
    respond_to do |format|
      if @mmlca.update(mmlca_params)
        format.html { redirect_to @mmlca, notice: 'Mmlca was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mmlca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mmlca/1
  # DELETE /mmlca/1.json
  def destroy
    @mmlca.destroy
    respond_to do |format|
      format.html { redirect_to mmlca_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mmlca
      @mmlca = Mmlca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mmlca_params
      params[:mmlca]
    end
end

app/helpers/intakes_helper.rb
module IntakesHelper
end

app/helpers/mmlca_helper.rb
module MmlcaHelper
end

app/helpers/mmlvs_helper.rb
module MmlvsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/regimen_helper.rb
module RegimenHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/mmlca/_form.html.erb
<%= form_for(@mmlca) do |f| %>
  <% if @mmlca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mmlca.errors.count, "error") %> prohibited this mmlca from being saved:</h2>

      <ul>
      <% @mmlca.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mmlca/edit.html.erb
<h1>Editing mmlca</h1>

<%= render 'form' %>

<%= link_to 'Show', @mmlca %> |
<%= link_to 'Back', mmlca_index_path %>

app/views/mmlca/index.html.erb
<h1>Listing mmlFs</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mmlca.each do |mmlca| %>
      <tr>
        <td><%= mmlca.id %><td>
        <td><%= link_to 'Show', mmlca %></td>
        <td><%= link_to 'Edit', edit_mmlca_path(mmlca) %></td>
        <td><%= link_to 'Destroy', mmlca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mmlca', new_mmlca_path %>

app/views/mmlca/new.html.erb
<h1>New mmlca</h1>

<%= render 'form' %>

<%= link_to 'Back', mmlca_index_path %>

app/views/mmlca/overview.html.erb
<h1>MML介護関連モジュール(Draft)概要</h1>
<p>2013年3月より介護に関連したモジュールについて仕様と実装例について検討を進めてきました。MMLがこれまで対象としてきた医療機関だけではなく、長期療養型施設群や在宅といった場面での利用も想定する必要があり、より多くの職種も関連します。</p>
<p>そうした多施設間連携、地域連携パスなど幅広い用途での使用にたえる規格を一つのモジュールとして作成することは不可能ですので、先行する要望として提案された<%= link_to "体温表モジュールと",mmlca_specification_path %>、<%= link_to "バイタルサインモジュール", mmlvs_specification_path %>を公開して広く意見を求めることとしました。</p>
<p>この規格はまだ試用段階であり、正式に決定されたものではありません。今後大きく仕様が変更される可能性がありますので、現時点でこの規格を利用したアプリケーションの実装は自己責任の範囲にとどめていただきますようお願いします。</p>
<p>この規格についての意見を募集しております。</p>
<p>このWebサイトでのソースコード一式は以下のサイトで公開しています。ライセンスはApache2です。<br/>
<a href="https://github.com/skoba/mml-rails">https://github.com/skoba/mml-rails</a>
</p>
<p>この仕様をまとめるにさいして、ご協力くださったみなさまにこの場を借りてお礼申し上げます。</p>
<h2>ToDo</h2>
  <ul>
    <li>エレメント解説</li>
    <li>MML0005テーブル module type 記載内容モジュールへの文書タイプ追加</li>
    <li>MML0007テーブル Gereration purpose 文書詳細モジュールへの文書タイプ追加</li>
    <li>MML0033テーブル vitalSign 熱型表項目の改訂・検討</li>
  </ul>
</ul>

<h2>ToDiscuss</h2>
<ul>
  <li>文字コードの移行：Shift-JIS -> UTF-8</li>
  <li>MML V4改訂に向けた準備</li>
  <li>DTDからXML Schemaへの移行</li>
  <li>タグの改廃について</li>
</ul>

app/views/mmlca/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mmlca_path(@mmlca) %> |
<%= link_to 'Back', mmlca_index_path %>

app/views/mmlca/table.html.erb
<section>
<article>
<h1>改訂されるテーブル一覧(Draft)</h1>
<h2>MML0005 Content Module type(記載内容モジュールの種別)</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>patientInfo</td>
  <td>patient module</td>
</tr>  
<tr>
  <td>healthInsurance</td>
  <td>health insurance module</td>
</tr>
<tr>
  <td>registeredDiagnosis</td>
  <td>registered diagnosis module</td>
</tr>
<tr>
  <td>lifestyle</td>
  <td>lifestyle module</td>
</tr>
<tr>
  <td>baseClinic</td>
  <td>base clinic module</td>
</tr>
<tr>
  <td>firstClinic</td>
  <td>first clinic module</td>
</tr>
<tr>
  <td>progressCourse</td>
  <td>progress course module</td>
</tr>
<tr>
  <td>surgery</td>
  <td>surgery module</td>
</tr>
<tr>
  <td>summary</td>
  <td>summary module</td>
</tr>
<tr>
  <td>claim</td>
  <td>予約請求モジュール</td>
</tr>
<tr>
  <td>claimAmount</td>
  <td>点数金額モジュール</td>
</tr>
<tr>
  <td>referral</td>
  <td>紹介状モジュール</td>
</tr>
<tr>
  <td>test</td>
  <td>検歴情報モジュール</td>
</tr>
<tr>
  <td>report</td>
  <td>報告書情報モジュール</td>
</tr>
<tr class="new">
  <td>vitalsign</td>
  <td>バイタルサインモジュール</td>
</tr>
<tr class="new">
  <td>flowsheet</td>
  <td>体温表モジュール</td>
</tr>
<tr class="new">
  <td>prescription</td>
  <td>内服処方箋モジュール</td>
</tr>
<tr class="new">
  <td>injection</td>
  <td>注射実施箋モジュール</td>
</tr>
</table>
<h2>MML0007 Generation purpose (文書詳細種別)</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>record</td>
  <td>診療記録</td>
</tr>
<tr>
  <td>recordAdmission</td>
  <td>入院時診療記録</td>
</tr>
<tr>
  <td>recordInpatient</td>
  <td>入院中診療経過記録</td>
</tr>
<tr>
  <td>recordConsult</td>
  <td>紹介時診療記録 (状態，処方，検査値等)</td>
</tr>
<tr>
  <td>recordDischarge</td>
  <td>退院時診療記録 (状態，処方，検査値等)</td>
</tr>
<tr>
  <td>recordOutpatient</td>
  <td>外来診療記録</td>
</tr>
<tr>
  <td>legalRecord</td>
  <td>法的義務に基づく診療記録</td>
</tr>
<tr>
  <td>consult</td>
  <td>紹介状</td>
</tr>
<tr>
  <td>report</td>
  <td>返書報告書</td>
</tr>
<tr>
  <td>reportRadiology</td>
  <td>放射線報告書</td>
</tr>
<tr>
  <td>reportPathology</td>
  <td>病理報告書</td>
</tr>
<tr>
  <td>reportTest</td>
  <td>検歴報告書</td>
</tr>
<tr>
  <td>summary</td>
  <td>要約</td>
</tr>
<tr>
  <td>summaryAdmission</td>
  <td>要約 (入院時)</td>
</tr>
<tr>
  <td>summaryPreoperation</td>
  <td>要約 (術前)</td>
</tr>
<tr>
  <td>summaryPostoperation</td>
  <td>要約 (術後)</td>
</tr>
<tr>
  <td>summaryMid</td>
  <td>要約 (中間)</td>
</tr>
<tr>
  <td>summaryDischarge</td>
  <td>要約 (退院時)</td>
</tr>
<tr>
  <td>summaryOutpatient</td>
  <td>要約 (外来)</td>
</tr>
<tr>
  <td>disclosure</td>
  <td>患者診療情報開示用</td>
</tr>
<tr>
  <td>informedConsent</td>
  <td>患者説明文書</td>
</tr>
<tr>
  <td>study</td>
  <td>研究用記録</td>
</tr>
<tr>
  <td>other</td>
  <td>その他</td>
</tr>
<tr>
  <td>claim</td>
  <td>医事情報</td>
</tr>
<tr class="new">
  <td>vitalsign</td>
  <td>バイタルサイン記録</td>
</tr>
<tr class="new">
  <td>flowsheet</td>
  <td>体温表</td>
</tr>
<tr class="new">
  <td>prescription</td>
  <td>内服処方箋モジュール</td>
</tr>
<tr class="new">
  <td>injection</td>
  <td>注射実施箋モジュール</td>
</tr>
</table>
</article>
<article>
<h1>追加されるテーブル一覧(Draft)</h1>
<h2>mmlVs01 バイタルサイン項目</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>Pulse rate</td>
  <td>脈拍</td>
</tr>
<tr>
  <td>Body temperature</td>
  <td>体温</td>
</tr>
<tr>
  <td>Systolic blood pressure</td>
  <td>収縮期血圧</td>
</tr>
<tr>
  <td>Diastolic blood pressure</td>
  <td>拡張期血圧</td>
</tr>
<tr>
  <td>SpO2</td>
  <td>経皮的酸素飽和度</td>
</tr>
<tr>
  <td>EtCO2</td>
  <td>呼気終末二酸化炭素濃度</td>
</tr>
<tr>
  <td>SaO2</td>
  <td>動脈血酸素飽和度</td>
</tr>
<tr>
  <td>PaO2</td>
  <td>動脈血酸素分圧</td>
</tr>
<tr>
  <td>PCO2</td>
  <td>動脈血二酸化炭素分圧</td>
</tr>
<tr>
  <td>Height</td>
  <td>身長</td>
</tr>
<tr>
  <td>Weight</td>
  <td>体重</td>
</tr>
<tr>
  <td>Blood sugar</td>
  <td>血糖値</td>
</tr>
</table>
<h2>mmlVs02 バイタルサイン測定単位</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>mmHg</td>
  <td>ミリメートル水銀柱高度</td>
</tr>
<tr>
  <td>centigrade</td>
  <td>摂氏温度</td>
</tr>
<tr>
  <td>/min</td>
  <td>一分あたりの回数</td>
</tr>
<tr>
  <td>%</td>
  <td>パーセント</td>
</tr>
<tr>
  <td>cm</td>
  <td>センチメートル</td>
</tr>
<tr>
  <td>kg</td>
  <td>キログラム</td>
</tr>
<tr>
  <td>mg/dl</td>
  <td>1デシリットルあたりのmg重量</td>
</tr>
</table>
<h2>mmlVs03 バイタルサイン体位名称テーブル</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>sitting</td>
  <td>坐位</td>
</tr>
<tr>
  <td>standing</td>
  <td>立位</td>
</tr>
<tr>
  <td>lying</td>
  <td>臥位</td>
</tr>
<tr>
  <td>reclining</td>
  <td>半座位</td>
</tr>
<tr>
  <td>tilting</td>
  <td>ティルティング位</td>
</tr>
</table>


<h2>mmlFs01 体温表モジュール摂食・飲水種別</h2>
体温表モジュールに記載する摂食・飲水の種別。食習慣の違いから国際的に統一したテーブルを作ることは困難であるため、日本での事例に合わせて項目を列記する。
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>朝食(主)</td>
  <td></td>
</tr>  
<tr>
  <td>朝食(副)</td>
  <td></td>
</tr>  
<tr>
  <td>昼食(主)</td>
  <td></td>
</tr>  
<tr>
  <td>昼食(副)</td>
  <td></td>
</tr>  
<tr>
  <td>夕食(主)</td>
  <td></td>
</tr>  
<tr>
  <td>夕食(副)</td>
  <td></td>
</tr>  
<tr>
  <td>夜食(主)</td>
  <td></td>
</tr>  
<tr>
  <td>夜食(副)</td>
  <td></td>
</tr>  
<tr>
  <td>おやつ</td>
  <td></td>
</tr>  
<tr>
  <td>補食</td>
  <td></td>
</tr>  
<tr>
  <td>経管栄養剤</td>
  <td></td>
</tr>  
<tr>
  <td>その他食事</td>
  <td></td>
</tr>  
<tr>
  <td>水分</td>
  <td></td>
</tr>  
<tr>
  <td>お茶</td>
  <td></td>
</tr>  
<tr>
  <td>ジュース</td>
  <td></td>
</tr>  
<tr>
  <td>その他飲料</td>
  <td></td>
</tr>
</table>
<h2>mmlFs02 体温表モジュール摂食・飲水単位</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>/10</td>
  <td>全量を10として、摂食できた分量</td>
</tr>  
<tr>
  <td>kcal</td>
  <td>キロカロリー摂取カロリー量</td>
</tr>  
<tr>
  <td>ml</td>
  <td>ミリリットル：摂取容量</td>
</tr>  
<tr>
  <td>g</td>
  <td>摂取したグラム重量</td>
</tr>  
<tr>
  <td>kg</td>
  <td>摂取したキログラム重量</td>
</tr>  
</table>
<h2>mmlFs03 体温表モジュール排泄種別</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>urine</td>
  <td>尿</td>
</tr>
<tr>
  <td>feces</td>
  <td>便</td>
</tr>
<tr>
  <td>blood</td>
  <td>血液</td>
</tr>
<tr>
  <td>bile</td>
  <td>胆汁</td>
</tr>
  <td>pleural effusion</td>
  <td>胸水</td>
</tr>
</tr>
  <td>ascites</td>
  <td>腹水</td>
</tr>
</tr>
  <td>other fluid</td>
  <td>その他の体液</td>
</tr>
</table>
<h2>mmlFs04 体温表モジュール排泄物単位</h2>
<table class="onecolumn">
<tr>
  <th>Value</th>
  <th>Description</th>
</tr>
<tr>
  <td>ml</td>
  <td>排泄したミリリットル容量</td>
</tr>  
<tr>
  <td>l</td>
  <td>排泄したリットル容量</td>
</tr>  
<tr>
  <td>g</td>
  <td>排泄したグラム重量</td>
</tr>  
<tr>
  <td>kg</td>
  <td>排泄したキログラム重量</td>
</tr>  
</table>
</article>
</section>