config/routes.rb
MmlCare::Application.routes.draw do
  get 'mmlca/overview' => 'mmlca#overview'
  get 'mmlca/specification' => 'mmlca#specification'
  get 'mmlca/table' => 'mmlca#table'
  get 'mmlvs/compare_vs_lb' => 'mmlvs#compare_vs_lb'
  get 'mmlvs/specification' => 'mmlvs#specification'
  get 'mmlca/sample_instance' => 'mmlca#sample_instance'
  get 'prescriptions/specification' => 'prescriptions#specification'
  get 'injections/specification' => 'injections#specification'

  resources :prescriptions
  resources :mmlca
  resources :mmlvs
  resources :people
  resources :services
  resources :observations
  resources :intakes
  resources :bodily_outputs
  resources :injections
  resources :regimen
  resources :medications
  resources :archetypes
  resources :nodes
  
  root to: 'mmlca#overview'

end

app/models/archetype.rb
class Archetype < ActiveRecord::Base
end

app/models/bodily_output.rb
class BodilyOutput < ActiveRecord::Base
  self.inheritance_column = :ar_type
end

app/models/injection.rb
class Injection < ActiveRecord::Base
  has_many :regimen

  def batch
    self.regimen.inject({}) do |rp, reg|
      if rp[reg.batch_no].nil?
        rp[reg.batch_no] = [reg]
      else
        rp[reg.batch_no] << reg
      end
      rp
    end
  end

end

app/models/intake.rb
class Intake < ActiveRecord::Base
  self.inheritance_column = :ar_type
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :prescription
end

app/models/mmlca.rb
class Mmlca < ActiveRecord::Base
  has_many :mmlvs
end

app/models/mmlvs.rb
class Mmlvs < ActiveRecord::Base
  has_many :vital_signs
  
  def sbp
    find_scoped_type('Systolic blood pressure')
  end

  def dbp
    find_scoped_type('Diastolic blood pressure')
  end

  def pulse
    find_scoped_type('Pulse rate')
  end

  def bt
    find_scoped_type('Body temperature')
  end

  def save
    vital_signs.each do |vs|
      vs.save
    end
    super
  end

  def update(params)
    VitalSign.create(type: 'Systolic plood pressure', val: params[:sbp], unit: 'mmHg', mmlvs_id: self.id)
    VitalSign.create(type: 'Diastolic blood pressure', val: params[:dbp], unit: 'mmHg',mmlvs_id: self.id)
    VitalSign.create(type: 'Pulse rate', val: params[:pulse], unit: '/min',mmlvs_id: :id)
    VitalSign.create(type: 'Body temperature', val: params[:bt], unit: 'centigrade',mmlvs_id: self.id)
    super
  end

  private

  def find_scoped_type(arg)
    vital_signs.select {|vs| vs.type == arg}.first
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
end

app/models/observation.rb
class Observation < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  has_many :medications

  def batch
    self.medications.inject({}) do |rp, med|
      if rp[med.batchNo].nil?
        rp[med.batchNo] = [med]
      else
        rp[med.batchNo] << med
      end
      rp
    end
  end
end

app/models/regimen.rb
class Regimen < ActiveRecord::Base
  belongs_to :injection
end

app/models/service.rb
class Service < ActiveRecord::Base
  self.inheritance_column = :ar_type
end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
  self.inheritance_column = :ar_type
  belongs_to :mmlvs

#  validates :val, numericality: {greater_than_or_equal_to: 0}
  scope :sbp, ->{ where type: 'Systolic blood pressure'}
#  default_scope { where published: true }
end

app/models/vschart.rb
class Vschart
  include ActiveModel::Model
  attr_accessor :sbp, :dbp, :pulse, :bt
  def initialize(args = { })
    self.sbp = args[:sbp]
    self.dbp = args[:dbp]
    self.pulse = args[:pulse]
    self.bt = args[:bt]
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:path, :atcode, :rmclass, :txt_value, :int_value, :flt_value)
    end
end

app/helpers/intakes_helper.rb
module IntakesHelper
end

app/helpers/mmlca_helper.rb
module MmlcaHelper
end

app/helpers/mmlvs_helper.rb
module MmlvsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/regimen_helper.rb
module RegimenHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :atcode %><br>
    <%= f.text_field :atcode %>
  </div>
  <div class="field">
    <%= f.label :rmclass %><br>
    <%= f.text_field :rmclass %>
  </div>
  <div class="field">
    <%= f.label :txt_value %><br>
    <%= f.text_field :txt_value %>
  </div>
  <div class="field">
    <%= f.label :int_value %><br>
    <%= f.number_field :int_value %>
  </div>
  <div class="field">
    <%= f.label :flt_value %><br>
    <%= f.text_field :flt_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Atcode</th>
      <th>Rmclass</th>
      <th>Txt value</th>
      <th>Int value</th>
      <th>Flt value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.path %></td>
        <td><%= node.atcode %></td>
        <td><%= node.rmclass %></td>
        <td><%= node.txt_value %></td>
        <td><%= node.int_value %></td>
        <td><%= node.flt_value %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @node.path %>
</p>

<p>
  <strong>Atcode:</strong>
  <%= @node.atcode %>
</p>

<p>
  <strong>Rmclass:</strong>
  <%= @node.rmclass %>
</p>

<p>
  <strong>Txt value:</strong>
  <%= @node.txt_value %>
</p>

<p>
  <strong>Int value:</strong>
  <%= @node.int_value %>
</p>

<p>
  <strong>Flt value:</strong>
  <%= @node.flt_value %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>